# Funding options for Git Time Machine Plus
# You can add your funding links here

github: [dilZhaan]
# patreon: your_patreon
# ko_fi: your_kofi
# custom: ['https://www.buymeacoffee.com/your_username']

